esphome:
  name: kaku

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key made with wizard"

ota:
  - platform: esphome


wifi:
  ssid: "ssid"
  password: "password"

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Kaku Fallback Hotspot"# Configuration entry
    password: "password"

output:
  - platform: gpio
    led_pin: LED
    #default pico spi
    miso_pin: MISO # GPIO 16
    mosi_pin: MOSI # GPIO 19
    sck_pin: SCK   # GPIO 18
    cs_pin: SS     # GPIO 17
    id: cc1101
