esphome:
  name: kaku

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key made with wizard"

ota:
  - platform: esphome


wifi:
  ssid: "ssid"
  password: "password"

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Kaku Fallback Hotspot"# Configuration entry
    password: "password"

cc1101:
  cs_pin: CS
  frequency: 433.92MHz
